name: proto_checks

on: [pull_request]

jobs:
  proto_checks:
    name: generating stubs from protos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: '0.36.0'
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Fetching base branch
        run: |
          git fetch -u origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Genereate proto Golang code
        uses: PxyUp/protoc-actions@v2.0.11
        with:
          path: -I$PROTO_DIR --go_opt=paths=source_relative --go_out=$GEN_OUT_DIR $(find $PROTO_DIR -type f -name '*.proto')
        env:
          GEN_OUT_DIR: ./
          PROTO_DIR: ./